### ISSUE TITLE
Regarding Contributer's Guide

### ISSUE THREAD

**Issue by pranayjoshi** [corvus-dotnet/Corvus.JsonSchema#314]
Hi, I was exploring Corvus.JsonSchema project and would like to know if there's any Contributer's Guide which I can refer to?
Thanks.

**Comment by pranayjoshi** [comment]
Also a keypoint, to install the tool onto mac systems, users need to use the following command: `export PATH="$PATH:/Users/pranayjoshi/.dotnet/tools` before installing the tool. Thanks

**Comment by mwadams** [comment]
First, thanks for getting involved!

Second re: MacOS that's a really useful piece of information! We tend to use the tools on Windows and Linux (under WSL) rather than MacOS - so any tips like that would be great. I've added this note to the README.md.

Third re: contributor's guide. Excellent point. I've added one to the repo. Let us know what else you'd like to know and we'll add it.
